/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Album: typeof import('./src/components/Music/ArtistDetail/Album.vue')['default']
    Desc: typeof import('./src/components/Music/ArtistDetail/Desc.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Mv: typeof import('./src/components/Recommend/Mv.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Newmusic: typeof import('./src/components/Recommend/Newmusic.vue')['default']
    RecommendedStations: typeof import('./src/components/Music/RecommendedStations.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sole: typeof import('./src/components/Music/Sole.vue')['default']
    Songsheet: typeof import('./src/components/Recommend/Songsheet.vue')['default']
    Tab: typeof import('./src/components/Music/Tab.vue')['default']
    Title: typeof import('./src/components/Recommend/Title.vue')['default']
    Video: typeof import('./src/components/Music/ArtistDetail/Video.vue')['default']
  }
}
