export interface hotAlbums {
    songs: [],
    paid: boolean,
    onSale: boolean,
    mark: number,
    awardTags: null,
    companyId: number,
    blurPicUrl: string,
    alias: [],
    artists: [
        {
            img1v1Id: number,
            topicPerson: number,
            followed: boolean,
            alias: [],
            picId: number,
            musicSize: number,
            albumSize: number,
            briefDesc: string,
            picUrl: string,
            img1v1Url: string,
            trans: string,
            name: string,
            id: number,
            img1v1Id_str: number
        }
    ],
    copyrightId: number,
    picId: number,
    artist: {
        img1v1Id: number,
        topicPerson: number,
        followed: boolean,
        alias: string[],
        picId: number,
        musicSize: number,
        albumSize: number,
        briefDesc: string,
        picUrl: string,
        img1v1Url: string,
        trans: string,
        name: string,
        id: number,
        picId_str: number,
        img1v1Id_str: number
    },
    publishTime: number,
    company: string,
    briefDesc: string,
    picUrl: string,
    commentThreadId: string,
    pic: number,
    description: string,
    tags: string,
    status: number,
    subType: string,
    name: string,
    id: number,
    type: string,
    size: number,
    picId_str: number,
    isSub: boolean
}